services:
  - type: web
    name: crm-gak
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: "GAK CRM"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_LOCALE
        value: id
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: PGSSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local

      # Diisi manual di dashboard Render (jangan ditaruh di file ini)
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
